// ============================================================
// KAIROS PRO — The Hub Types
// Shared TypeScript interfaces for the entire Hub service
// ============================================================

/** Signal conviction levels */
export type ConvictionLevel = 'EXECUTE' | 'CAUTION' | 'HOLD';

/** Trade direction */
export type TradeDirection = 'LONG' | 'SHORT';

/** Raw simulation result from The Brain */
export interface SimulationResult {
  symbol: string;
  timeframe: '15m' | '60m';
  win_probability: number;
  median_target_price: number;
  risk_floor_price: number;
  suggested_leverage: number;
  suggested_direction: TradeDirection;
  simulation_count: number;
  consensus_paths: number;
  mode_target_price: number;
  percentile_5_price: number;
  current_price: number;
  up_paths_count: number;
  down_paths_count: number;
  timestamp: string;
}

/** Trade verdict generated by the Hub */
export interface TradeVerdict {
  id: string;
  symbol: string;
  status: ConvictionLevel;
  direction: TradeDirection;
  probability: number;
  entry_price: number;
  take_profit: number;
  stop_loss: number;
  leverage: number;
  margin_percent: number;
  risk_reward_ratio: number;
  timeframe: '15m' | '60m';
  message: string;
  timestamp: string;
  simulation_meta: {
    total_simulations: number;
    winning_paths: number;
    mode_target: number;
    floor_price: number;
  };
}

/** WebSocket event types */
export type WSEventType =
  | 'TRADE_ALERT'
  | 'SIGNAL_UPDATE'
  | 'AGENT_UPDATE'
  | 'WATCHER_ALERT'
  | 'SYSTEM_STATUS'
  | 'HEARTBEAT'
  | 'PRICE_FEED'
  | 'ERROR';

/** WebSocket message envelope */
export interface WSMessage<T = unknown> {
  event: WSEventType;
  data: T;
  timestamp: string;
  sequence: number;
}

/** System status payload */
export interface SystemStatus {
  hub: 'ONLINE' | 'DEGRADED' | 'OFFLINE';
  brain: 'ONLINE' | 'DEGRADED' | 'OFFLINE';
  pulse: 'ONLINE' | 'DEGRADED' | 'OFFLINE';
  uptime_seconds: number;
  active_connections: number;
  last_simulation: string | null;
}

/** Price feed data */
export interface PriceFeed {
  symbol: string;
  price: number;
  change_24h: number;
  volume_24h: number;
  timestamp: string;
}

/** Simulation request to The Brain */
export interface SimulationRequest {
  symbol: string;
  timeframe: '15m' | '60m';
  price_data: number[];
  current_price: number;
}
